### PR TITLE
Sim1 Adjustments based on first review

### PR DESCRIPTION
**Pull request by lkosanke**
* Added fixed values where possible
* Added repetition mechanism with seed based on furrr

### CODE REVIEW

**Comment by lkosanke** [comment]
Todo:
* Calculate performance measures (extract results()?)
* Get rid of loops in report_analysis()

Open question:
Is it efficient to treat the repetitions like the other design variables? The df will become quite large (52.500 rows for 15000 repetitions)

**Comment by lkosanke** [comment]
Got rid of all loops, should there be more furr?

**Review by aaronpeikert — APPROVED** [review]

**Comment by aaronpeikert** [comment]
How many levels of furrr depends on the execution strategy. It is usually a good idea to parrallelize the repetitions (i.e., each job consists of one repetition of the same design matrix with different seed) because then each job takes the same time but your needs may vary.

**Comment by aaronpeikert** [comment]
> Open question: Is it efficient to treat the repetitions like the other design variables? The df will become quite large (52.500 rows for 15000 repetitions)

50.000 rows isnt all that much. As long as the data frame gets reconstructed only a couple of times (ones before fitting, ones after, ones for calculating the performance measures) absolutely now problem. It would be much more inefficient to for example build 5000x 1000 rows of dataframes.

**Pull request merged**
